### ISSUE TITLE
DMC_DUBIOUS_MAP_COLLECTION and WOC_WRITE_ONLY_COLLECTION_FIELD false positive if used in anonymous class

### ISSUE THREAD

**Issue by vbrandl** [mebigfatguy/fb-contrib#408]
`fb-contrib` has false positives for the `DMC_DUBIOUS_MAP_COLLECTION` and `WOC_WRITE_ONLY_COLLECTION_FIELD` if access to the according fields only happens in an instance of an anonymous class via `OuterClass.this.someCollection`

I created a [testcase to reproduce the issue](https://github.com/vbrandl/fb-contrib-collections-testcase). Here is the [actual source](https://github.com/vbrandl/fb-contrib-collections-testcase/blob/master/src/main/java/spotbugs_reprod/App.java):

<details><summary>Click to expand</summary><p>

```java
package spotbugs_reprod;

import java.util.HashSet;
import java.util.Map;
import java.util.Set;

public class App {
    private final Set<Integer> insertedValues = new HashSet<>();
    private final Map<Integer, String> someMap = Map.of(1, "1", 2, "2", 3, "3", 8, "1337");

    public void handleMessage(Message msg) {
        msg.match(new Message.Matcher<Void>() {
            @Override
            public Void is(Add a) {
                App.this.insertedValues.add(a.val);
                return null;
            }

            @Override
            public Void is(Calc c) {
                var sum = App.this.insertedValues.stream().reduce(0, (a, b) -> a + b);
                System.out.println(sum);
                System.out.println(App.this.someMap.get(sum));
                App.this.insertedValues.clear();
                return null;
            }
        });
    }

    public static void main(String[] args) {
        var app = new App();

        app.handleMessage(new Add(3));
        app.handleMessage(new Add(5));
        app.handleMessage(new Calc());

    }

    // public void doStuff() {
    //     this.insertedValues.add(1337);

    //     var sum = this.insertedValues.stream().reduce(0, (a, b) -> a + b);
    //     System.out.println(sum);
    //     System.out.println(this.someMap.get(sum));
    //     this.insertedValues.clear();
    // }

    interface Message {
        <T> T match(Matcher<T> matcher);

        interface Matcher<T> {
            T is(Add a);

            T is(Calc c);
        }
    }

    static final class Add implements Message {
        final int val;
        Add(int val) {
            this.val = val;
        }

        @Override
        public <T> T match(Matcher<T> matcher) {
            return matcher.is(this);
        }
    }
    static final class Calc implements Message {
        @Override
        public <T> T match(Matcher<T> matcher) {
            return matcher.is(this);
        }
    }
}
```

</p>
</details>

If the `doStuff` method, that directly accesses the collections using `this` is commented in, `fb-contrib` will not produce the mentioned lints.

**Comment by mttjj** [comment]
This doesn't only occur with anonymous classes. I am uplifting our projects to Java 11 from Java 8 and am encountering a few hundred false-positives (235 to be exact) on `WOC_WRITE_ONLY_COLLECTION_FIELD` that are not flagged with Java 8. 

Here is a very simple class that reproduces the issue:

```java
public class FooBar {
    private final List<String> bars = new ArrayList<>();

    public void addBar(String bar) {
        bars.add(bar);
    }

    public void runFoo() {
        new Foo().run();
    }

    private class Foo implements Runnable {
        @Override
        public void run() {
            bars.forEach(System.out::println);
        }
    }
}
```

This pattern is abundant throughout our codebase.

**Comment by mebigfatguy** [comment]
it's the forEach i believe, i think this was fixed, try 7.6.2

**Comment by mebigfatguy** [comment]
reopen if  not.

**Comment by vbrandl** [comment]
I just updated the test repository and the problem still exists for me: https://github.com/vbrandl/fb-contrib-collections-testcase

I tried using both Java 11 and Java 19.

Edit: I cannot reopen the issue

**Comment by mebigfatguy** [comment]
yes, i think the simple example above is fixed, but the anon only use case still holds. i shouldn't have closed it. thanks.

**Comment by vbrandl** [comment]
Can you reopen the issue or should I create a new one?
